variables:
    REGISTRY: docker.edge.tmecosys.com

build:
  stage: build
  allow_failure: false
  variables:
    REGISTRY: docker.edge.tmecosys.com
    PREFIX: metrics/instana-agent-static
  only:
    refs:
      - master
  image: docker
  tags:
    - multistage
    - europe
  before_script:
    - apk add --update make git
  script:
    - docker login $ARTIFACTORY_SERVER -u $ARTIFACTORY_USER -p $ARTIFACTORY_API_KEY
    - make all
